export const ADD_EDIT_RECIPE_SUCCESS = "ADD_EDIT_RECIPE_SUCCESS";
export const ADD_EDIT_RECIPE_ERROR = "ADD_EDIT_RECIPE_ERROR";

export const CHOOSE_MEAL_SUCCESS = "CHOOSE_MEAL_SUCCESS";
export const CHOOSE_MEAL_ERROR = "CHOOSE_MEAL_ERROR";

export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_ERROR = "DELETE_RECIPE_ERROR";

export const GET_GROCERIES_BEGIN = "GET_GROCERIES_BEGIN";
export const GET_GROCERIES_SUCCESS = "GET_GROCERIES_SUCCESS";
export const GET_GROCERIES_ERROR = "GET_GROCERIES_ERROR";

export const GET_MEALS_BEGIN = "GET_MEALS_BEGIN";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";

export const GET_RECIPES_BEGIN = "GET_RECIPES_BEGIN";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_ERROR = "GET_RECIPES_ERROR";

export const LOADING_FINISHED = "LOADING_FINISHED";
export const LOADING_STARTED = "LOADING_STARTED";
export const SET_DAYS_TO_PROVIDE = "SET_DAYS_TO_PROVIDE";
export const SET_NEW_AMOUNT = "SET_NEW_AMOUNT";
export const SET_USER_DATA = "SET_USER_DATA";
